### ISSUE TITLE
Add more to the removing images and containers section

### ISSUE THREAD

**Issue by sstevens2** [UW-Madison-DataScience/docker-introduction#2]
Images and containers can eat up space on a machine so I'd like to demo removing them. Esp since you can't remove an image if you have hanging containers from it.

- [x] Show that removing an image doesn't work if you have hanging containers
- [x] Show how to remove the containers
- [x] Show how to remove the image
- [x] Tell them about the 'prune' but don't demo

**Comment by rdimond** [comment]
"I can try to remove remove the hello-world image with a docker image rm command that includes the image name, such as:"

On my first reading I thought "image name" was referring to the image ID, and that the following command failed because it didn't use the image ID. Since docker image ls labels it "Repository" I'd suggest using "Repository name."

I'd also suggest giving the student a bit of a road map at that point: we can't remove the image because a container based on it is still "in use" even though it exited, we'll learn how to identify and shut down such containers, then we'll be able to remove the image.

**Comment by rdimond** [comment]
Note that 'docker container ps -all' works but shows only the most recently run container rather than all of them. (You can guess how I figured that out.) I'll let you decide if - vs. -- is worth a mention or just something for helpers to watch out for.

**Comment by sstevens2** [comment]
Interestingly `docker container ps -all` doesn't list the exited ones but `docker container ps --all` does...
